# Generated by Django 4.2.6 on 2023-11-24 07:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('network_address', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\.\\d+)*\\Z'), code='invalid', message=None)])),
                ('broadcast', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\.\\d+)*\\Z'), code='invalid', message=None)])),
                ('prefix', models.PositiveIntegerField()),
                ('mask', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\.\\d+)*\\Z'), code='invalid', message=None)])),
                ('wildcard', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\.\\d+)*\\Z'), code='invalid', message=None)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subNet.net')),
            ],
        ),
    ]
