# Generated by Django 5.0 on 2024-02-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subNet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='net',
            name='author',
        ),
        migrations.RemoveField(
            model_name='net',
            name='description',
        ),
    ]
