# Generated by Django 5.0 on 2024-02-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subNet', '0002_remove_net_author_remove_net_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='net',
            name='network_name',
        ),
    ]
