# Generated by Django 5.0 on 2024-02-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subNet', '0003_remove_net_network_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='net',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
