# Generated by Django 5.0 on 2024-02-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subNet', '0004_net_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='net',
            name='title_slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
